package by.epamtr.totalizator.command;

public enum CommandName {
	SIGN_IN, GO_TO_REGISTRATION, REGISTRATION_USER, SIGN_OUT, SHOW_EVENTS, UNKNOWN, GO_TO_GAME_CREATION,
	GAME_CREATION,GO_TO_ADMIN_PAGE, GO_TO_INDEX_PAGE, GO_TO_ERROR_PAGE, CHANGE_LANGUAGE, GO_TO_EVENT_CREATION, 
	EVENT_CREATION, GO_TO_SEARCH_EVENT, SEARCH_MATCHING_EVENTS, EVENT_GAME_MATCHING, GO_TO_EDIT_SEARCH_EVENT,
	SEARCH_ALL_EVENTS, GO_TO_EVENT_EDIT, EDIT_EVENT, INIT_CONNECTION_POOL, MAKE_BET, GO_TO_BET_SUBMIT,
	UNMATCH_EVENT, DELETE_EVENT, CLOSE_GAME_COUPON, GO_TO_GAME_COUPON_DETAILS, EDIT_GAME_COUPON
}
